spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: com.jkk.aihome.configurator.SQLiteDialect
    show-sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1

udp:
  port: 23333
  conn-str: aihome-connect
